name: Save IPA

on:
  workflow_dispatch:
    inputs:
      deb:
        description: "Direct URL to deb file"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Git identity
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Download deb file
        run: |
          curl -L -o ${{ github.workspace }}/app.deb "${{ github.event.inputs.deb }}"

      - name: Extract deb file name (without extension)
        id: deb_filename
        run: |
          echo "::set-output name=filename::$(basename ${{ github.workspace }}/app.deb .deb)"

      - name: Convert deb to IPA
        run: |
          dpkg-deb -X ${{ github.workspace }}/app.deb ${{ github.workspace }}/app
          cd ${{ github.workspace }}/app/Applications
          zip -r ${{ github.workspace }}/${{ steps.deb_filename.outputs.filename }}.ipa .

      - name: Move IPA file to IPAs folder
        run: |
          mkdir -p ${{ github.workspace }}/IPAs
          mv ${{ github.workspace }}/${{ steps.deb_filename.outputs.filename }}.ipa ${{ github.workspace }}/IPAs

      - name: Edit README file with download link
        run: |
          echo "Download the IPA file [here](https://github.com/ArielGavrielov/deb-to-ipa/blob/main/IPAs/${{ steps.deb_filename.outputs.filename }}.ipa)" >> ${{ github.workspace }}/IPAs/README.md

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs

      - name: Track IPA file and README with Git LFS
        run: |
          git lfs install
          git lfs track 'IPAs/*'

      - name: Commit and push changes using GITHUB_TOKEN
        run: |
          git add ${{ github.workspace }}/IPAs
          git commit -m "Add ${{ steps.deb_filename.outputs.filename }}.ipa and update README"
          git push -u origin main

      - name: Set action summary with full URL
        run: |
          echo "::set-output name=summary::Download the IPA file [here](https://github.com/ArielGavrielov/deb-to-ipa/blob/main/IPAs/${{ steps.deb_filename.outputs.filename }}.ipa)"
