name: Run

on:
  workflow_dispatch:
    inputs:
      deb:
        description: "Direct URL to deb file"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
          with:
            token: ${{ secrets.GH_PAT }}
      - name: Set up Git identity
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Download deb file
        run: |
          curl -L -o ${{ github.workspace }}/app.deb "${{ github.event.inputs.deb }}"

      - name: Convert deb to IPA
        run: |
          dpkg-deb -X ${{ github.workspace }}/app.deb ${{ github.workspace }}/app
          cd ${{ github.workspace }}/app/Applications
          zip -r ${{ github.workspace }}/App.ipa .

      - name: Move IPA file to IPAs folder
        run: |
          mkdir -p ${{ github.workspace }}/IPAs
          mv ${{ github.workspace }}/App.ipa ${{ github.workspace }}/IPAs

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs

      - name: Track IPA file with Git LFS
        run: |
          git lfs install
          git lfs track 'IPAs/*'

      - name: Commit using GITHUB_TOKEN
        run: |
          git add ${{ github.workspace }}/IPAs
          git commit -m "Add App.ipa"

      - name: Push using Personal Access Token (PAT)
        run: |
          git remote set-url origin "https://github.com/ArielGavrielov/deb-to-ipa.git"
          git push -u origin main -o "PersonalAccessToken=${{ secrets.GH_PAT }}"
