name: Test

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Print Git Remotes
        run: |
          git remote remove origin
          git remote add origin https://${{secrets.GH_PAT}}@github.com/ArielGavrielov/deb-to-ipa
          git remote -v
