name: Test

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Print Git Remotes
        run: |
          git remote set-url origin https://ArielGavrielov:${{secrets.GH_PAT}}@github.com/ArielGavrielov/deb-to-ipa.git
          git remote -v
