name: Push commit
on: push
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GH_PAT}}
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'Ariel'
          git config --global user.email 'ArielGavrielov@users.noreply.github.com'
          git commit -am "Automated report"
          git push